spring:
  datasource:
    url: jdbc:mysql://localhost:3306/natural_id_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
    hikari:
      auto-commit: false
      data-source-properties:
        rewriteBatchedStatements: true
        profileSQL: true
        logger: Slf4JLogger
        maxQuerySizeToLog: 999999
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        check_nullability: true

---
spring:
  config:
    activate.on-profile: beta

natural-id-sample:
  discount:
    start-date: 2024-04-30
    end-date: 2024-04-30
    ids:
      - 1
      - 5
      - 7
    keys:
      - PRODUCT_AAA
      - PRODUCT_CCC
      - PRODUCT_EEE
      - PRODUCT_XXX

---
spring:
  config:
    activate.on-profile: prod

natural-id-sample:
  discount:
    start-date: 2024-05-01
    end-date: 2024-05-10
    ids:
      - 1
      - 3
      - 5
      - 6
    keys:
      - PRODUCT_AAA
      - PRODUCT_CCC
      - PRODUCT_EEE
      - PRODUCT_XXX