version: '3.8'

services:
  test-mysql:
    container_name: mysql8
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d